import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
    headerView:{
        height:55,
        paddingHorizontal:15,
        backgroundColor:'#071B36',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    headerTitle:{
        flexDirection:'row',
        alignItems:'center',
        flex:1
    },
    headerText:{
        color:'#fff',
        fontFamily:'Inter-SemiBold',
        fontSize:16,
        marginLeft:10,
    },
    bodyView:{
        padding:15,
    },
    recomandedText:{
        fontFamily:'Inter-SemiBold',
        fontSize:16,
        color:'#071B36'
    },
    recomandedUsers:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:15
    },
    recomandedUsersPic:{
        flexDirection:'row',
        alignItems:'center'
    },
    userInfo:{
        marginLeft:10
    },
    UsersProfilePic:{
        width:40,
        height:40,
        borderRadius:50
    },
    hospitalName:{
        fontFamily:'Inter-Regular',
        color:'#071B36'
    },
    groupsText:{
        fontSize:12,
        fontFamily:'Inter-Regular',
        color:'#51668A'
    },
    joinText:{
        fontSize:12,
        fontFamily:'Inter-Regular',
        color:'#2376E5'
    },

    //------------------------Join community----------------------------
    UserComments:{
        alignItems:'center',
        position:'absolute',
        bottom:0,
        borderTopWidth:1,
        width:Dimensions.get('window').width,
        borderColor:'#ccc',
        backgroundColor:'#fff',
        justifyContent:'center',
        paddingHorizontal:15
      },
      UserInnerComments:{
        alignItems:'center',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:'#ecf2f6',
        borderRadius:50,
        margin:7,
        padding:7,
        flex:1,
        width:Dimensions.get('window').width/1.03,
      },
      input:{
        width:Dimensions.get('window').width/1.6,
        height:50,
        paddingLeft:10,
      },
      iconsContainer:{
        flexDirection:'row',
        
      },
      inputCont:{
        flexDirection:'row'
      },
      usersCommentContainer:{
        flexDirection:'row',
        paddingBottom:20,
        justifyContent:'space-between',
        alignItems:'center'
      },
      usersCommentPictureContainer:{
        flexDirection:'row',
      },
      userUsername:{
        fontFamily:'Inter-SemiBold'
      },
      userCommentTexts:{
        fontFamily:'Inter-Regular',
        width:Dimensions.get('window').width/1.3,
        textAlign:'justify'
      },
      NoCommentTexts:{
        fontFamily:'Inter-SemiBold',
        alignSelf:'center',
      },
});